using System.Collections.Generic;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using RTLForge.Arabic;

namespace RTLForge.EditorTools
{
    /// <summary>
    /// RTL Forge — Arabic Text Test.
    /// Processes raw Arabic text through the shaping + RTL prototype and lets you
    /// compare the original string against the processed one in TextMeshPro.
    /// Also runs unit-style verification cases for the shaper and reordering.
    /// </summary>
    public class RTLForgeArabicTestWindow : EditorWindow
    {
        private const string GeneratedFontsFolder = "Assets/RTLForge/GeneratedFonts";

        private string _rawText = "مرحبا بالعالم";
        private string _processed = "";
        private readonly StringBuilder _output = new StringBuilder();
        private Vector2 _scroll;

        [MenuItem("Tools/RTL Forge/Arabic Text Test")]
        public static void Open()
        {
            var window = GetWindow<RTLForgeArabicTestWindow>();
            window.titleContent = new GUIContent("RTL Forge — Arabic Text Test");
            window.minSize = new Vector2(440, 520);
        }

        private void OnGUI()
        {
            EditorGUILayout.LabelField("Raw Text", EditorStyles.boldLabel);
            _rawText = EditorGUILayout.TextArea(_rawText, GUILayout.MinHeight(60));

            if (GUILayout.Button("Process Text", GUILayout.Height(26)))
            {
                _processed = RTLProcessor.ProcessRTL(_rawText);
                _output.AppendLine("Original:  " + _rawText);
                _output.AppendLine("Shaped:    " + ArabicShaper.ShapeArabic(_rawText));
                _output.AppendLine("Processed: " + _processed);
            }

            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField("Processed Output", EditorStyles.boldLabel);
            EditorGUILayout.SelectableLabel(
                string.IsNullOrEmpty(_processed) ? "—" : _processed,
                GUI.skin.textArea, GUILayout.MinHeight(50));

            if (GUILayout.Button("Create TMP Test"))
                CreateTmpTest();

            EditorGUILayout.Space(10);
            EditorGUILayout.LabelField("Verification", EditorStyles.boldLabel);
            if (GUILayout.Button("Run Tests"))
                RunTests();

            EditorGUILayout.HelpBox(
                "Glyph availability vs. shaping: the processed string uses Arabic " +
                "Presentation Forms-B codepoints. The Font Asset from the Font Generator " +
                "must include those presentation forms in its character set, otherwise " +
                "TMP shows missing-glyph boxes. Add the processed characters to the " +
                "Font Generator's character set and regenerate if needed.", MessageType.Info);

            if (GUILayout.Button("Copy Character Set For Font Generator"))
                CopyShapedCharset();

            EditorGUILayout.Space(6);
            _scroll = EditorGUILayout.BeginScrollView(_scroll, GUILayout.ExpandHeight(true));
            EditorGUILayout.SelectableLabel(_output.ToString(), GUI.skin.textArea, GUILayout.ExpandHeight(true));
            EditorGUILayout.EndScrollView();
        }

        /// <summary>
        /// Canvas + two TextMeshProUGUI labels (original vs processed) using the
        /// Font Asset generated by the RTL Forge Font Generator, if available.
        /// </summary>
        private void CreateTmpTest()
        {
            if (string.IsNullOrEmpty(_processed))
                _processed = RTLProcessor.ProcessRTL(_rawText);

            TMP_FontAsset fontAsset = LoadGeneratedFontAsset();

            var canvasGO = new GameObject("RTLForge_ArabicTest_Compare", typeof(Canvas), typeof(CanvasScaler));
            var canvas = canvasGO.GetComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasGO.GetComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;

            CreateLabel(canvasGO.transform, new Vector2(0, 90), "Original (raw)",
                _rawText, TextAlignmentOptions.Right, fontAsset);
            CreateLabel(canvasGO.transform, new Vector2(0, -90), "Processed (shaped + RTL)",
                _processed, TextAlignmentOptions.Left, fontAsset);

            Undo.RegisterCreatedObjectUndo(canvasGO, "RTL Forge — Arabic TMP Test");
            Selection.activeGameObject = canvasGO;

            _output.AppendLine("TMP test object created" + (fontAsset != null
                ? " with font asset: " + fontAsset.name
                : " (no generated font asset found — using TMP default. Regenerate the Font Asset with the presentation-forms character set)."));
        }

        private static void CreateLabel(Transform parent, Vector2 anchoredPos, string header,
            string text, TextAlignmentOptions alignment, TMP_FontAsset fontAsset)
        {
            var go = new GameObject(header.Replace(' ', '_'));
            go.transform.SetParent(parent, false);
            var rect = go.AddComponent<RectTransform>();
            rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.5f);
            rect.anchoredPosition = anchoredPos;
            rect.sizeDelta = new Vector2(800, 120);

            var tmp = go.AddComponent<TextMeshProUGUI>();
            if (fontAsset != null) tmp.font = fontAsset;
            tmp.text = header + "\n" + text;
            tmp.fontSize = 34;
            tmp.alignment = alignment;
            tmp.textWrappingMode = TextWrappingModes.Normal;
        }

        private static TMP_FontAsset LoadGeneratedFontAsset()
        {
            foreach (var guid in AssetDatabase.FindAssets("t:TMP_FontAsset", new[] { GeneratedFontsFolder }))
            {
                var asset = AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(AssetDatabase.GUIDToAssetPath(guid));
                if (asset != null) return asset;
            }
            return null;
        }

        /// <summary>
        /// Copies the base + presentation-forms characters needed to render the current
        /// text, so they can be pasted into the Font Generator's character set.
        /// </summary>
        private void CopyShapedCharset()
        {
            string shaped = ArabicShaper.ShapeArabic(_rawText);
            var unique = new HashSet<char>(shaped);
            var sb = new StringBuilder();
            foreach (var c in unique) sb.Append(c);
            EditorGUIUtility.systemCopyBuffer = sb.ToString();
            _output.AppendLine("Copied " + unique.Count + " unique shaped characters to clipboard — paste into Font Generator and regenerate.");
        }

        // ---------------- verification cases ----------------

        private readonly struct TestCase
        {
            public readonly string Name;
            public readonly string Input;
            public readonly string Expected;
            public TestCase(string name, string input, string expected)
            {
                Name = name; Input = input; Expected = expected;
            }
        }

        private void RunTests()
        {
            _output.AppendLine("— Running shaping tests —");

            // Expected codepoints derived from the Unicode Presentation Forms-B tables.
            var cases = new List<TestCase>
            {
                // مرحبا: م initial, ر final, ح medial, ب medial, ا final
                new TestCase("مرحبا", "\u0645\u0631\u062D\u0628\u0627",
                    "\uFEE3\uFEAE\uFEA4\uFE92\uFE8E"),
                // سلام: س initial, ل medial, ا final, م isolated (after non-joining ا)
                new TestCase("سلام", "\u0633\u0644\u0627\u0645",
                    "\uFEB3\uFEDE\uFE8E\uFEE1"),
                // كتاب: ك initial, ت medial, ا final, ب isolated
                new TestCase("كتاب", "\u0643\u062A\u0627\u0628",
                    "\uFEDB\uFE98\uFE8E\uFE8F"),
                // مدرسة: م initial, د final, ر isolated (د doesn't join forward),
                // س initial, ة final
                new TestCase("مدرسة", "\u0645\u062F\u0631\u0633\u0629",
                    "\uFEE3\uFEAA\uFEAD\uFEB3\uFE94"),
                // محمد
                new TestCase("محمد", "\u0645\u062D\u0645\u062F",
                    "\uFEE3\uFEA4\uFEE4\uFEAA"),
                // العربية: ا isolated, ل initial, ع medial, ر isolated,
                // ب initial, ي medial, ة final
                new TestCase("العربية", "\u0627\u0644\u0639\u0631\u0628\u064A\u0629",
                    "\uFE8D\uFEDF\uFECB\uFEAD\uFE91\uFEF4\uFE94"),
                // isolated letters: د does not join
                new TestCase("د د", "\u062F \u062F", "\uFEA9 \uFEA9"),
                // lam-alef mandatory ligature (isolated and final)
                new TestCase("لا", "\u0644\u0627", "\uFEFB"),
                // ولا: و isolated (doesn't join forward) → lam-alef isolated ligature
                new TestCase("ولا", "\u0648\u0644\u0627", "\uFEED\uFEFB"),
            };

            int pass = 0;
            foreach (var tc in cases)
            {
                string shaped = ArabicShaper.ShapeArabic(tc.Input);
                bool ok = shaped == tc.Expected;
                if (ok) pass++;
                _output.AppendLine((ok ? "PASS " : "FAIL ") + tc.Name +
                    (ok ? "" : "  got " + Codepoints(shaped) + " expected " + Codepoints(tc.Expected)));
            }

            _output.AppendLine("— RTL ordering checks —");
            RunOrderingCheck("مرحبا بالعالم");
            RunOrderingCheck("السعر: ١٢٣");
            RunOrderingCheck("مرحبا World");
            RunOrderingCheck("Hello مرحبا");
            RunOrderingCheck("هل أنت متأكد؟");
            RunOrderingCheck("بسم الله");

            _output.AppendLine("Shaping: " + pass + "/" + cases.Count + " passed.");
        }

        private void RunOrderingCheck(string input)
        {
            string processed = RTLProcessor.ProcessRTL(input);
            bool digitsIntact = true;
            bool latinIntact = true;

            // Digits and Latin runs must survive reordering with their order intact.
            if (ContainsAny(input, "0123456789٠١٢٣٤٥٦٧٨٩"))
                digitsIntact = ExtractRun(processed, c => char.IsDigit(c) || ArabicCharacterDatabase.IsArabicDigit(c))
                    == ExtractRun(input, c => char.IsDigit(c) || ArabicCharacterDatabase.IsArabicDigit(c));
            if (ContainsAny(input, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"))
                latinIntact = ExtractRun(processed, char.IsLetter)
                    .IndexOfAny("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".ToCharArray()) >= 0;

            _output.AppendLine((digitsIntact && latinIntact ? "OK   " : "FAIL ") + input +
                "  →  " + processed + "  (digits intact: " + digitsIntact + ", latin intact: " + latinIntact + ")");
        }

        private static bool ContainsAny(string s, string chars)
        {
            foreach (var c in s) if (chars.IndexOf(c) >= 0) return true;
            return false;
        }

        private static string ExtractRun(string s, System.Func<char, bool> match)
        {
            var sb = new StringBuilder();
            foreach (var c in s) if (match(c)) sb.Append(c);
            return sb.ToString();
        }

        private static string Codepoints(string s)
        {
            var sb = new StringBuilder();
            foreach (var c in s) sb.Append(((int)c).ToString("X4")).Append(' ');
            return sb.ToString().Trim();
        }
    }
}
